---
version: '3.7'

services:
  front:
    build:
      context: apps/front
      dockerfile: Dockerfile
    restart: on-failure

  graphql:
    build:
      context: apps/graphql
      dockerfile: Dockerfile
    restart: on-failure

  mongo:
    image: 'mongo:3.2.20-jessie'
    restart: on-failure

